name: Run MATLAB
on: [push]
jobs:
  my-job:
    name: Run MATLAB
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: |
            % Set up timer to kill MATLAB
            t = timer('TimerFcn', @(~,~)system(sprintf("taskkill /pid %d /f", feature('getpid'))), 'StartDelay', 30);
            start(t);
            pause(60);
      - name: Marker
        if: failed()
        run: echo here
